version: 2

builds:
  - binary: gast
    main: .
    ldflags:
      - -s -w
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

brews:
  - repository:
      owner: pataar
      name: homebrew-tap
    directory: Formula
    homepage: https://github.com/pataar/gast
    description: GitLab Activity Stream TUI

changelog:
  use: github
  sort: asc
  groups:
    - title: Features
      regexp: '^.*?feat(\(.+\))?!?:.+$'
      order: 0
    - title: Bug fixes
      regexp: '^.*?fix(\(.+\))?!?:.+$'
      order: 1
    - title: Other
      order: 999
  filters:
    exclude:
      - '^build\(deps\):'
      - "^chore:"
      - "^docs:"
      - "^test:"
